version: "3.8"

services:
  client:
    build: ./client
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000

  server:
    build: ./server
    ports:
      - 8000:8000
    environment:
      DB_URL: mongodb://db/mockdb

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mockdata:/data/db

volumes:
  mockdata:
